### ISSUE TITLE
Napply turns off automatically

### ISSUE THREAD

**Issue by seb1** [thibault/Miximum-apps#12] opened 2013-07-25 05:31 UTC
Thank you for a nice app. I have the following problem: When the screen is turned off, the Napply alarm stops after ~1 second and the screen is not turned on. If the screen is on from the beginning, it works as expected. I am using Android 4.1.2 on a Galaxy Note II.

**Comment by thibault** [comment] 2013-09-02 15:48
Sorry, unable to reproduce. Closing this bug right now.

**Closed as completed by thibault** 2013-09-02 15:48 UTC
